spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/blackkensai/microservice-config.git
        svn:
          uri: http://run-svn/projects/cn/E-Commerce/branch/FRAMEWORK/microservice-sample-config/nh
  profiles:
    active:
    - subversion
server:
  port: 8888
management:
  security:
    enabled: false