server:
  port: 9000
spring:
  application:
    name: spring-cloud-zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
    register-with-eureka: false
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false