server:
  port: 0
spring:
  application:
    name: spring-cloud-order-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${random.int}
orderclient:
  ribbon:
    ConnectTimeout: 2000
    ReadTimeout: 2000
    hystrixTimeout: 1000
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 1
    OkToRetryOnAllOperations: true
    ServerListRefreshInterval: 2000
